options(repos = c(CRAN = "http://cran.rstudio.com"))
pkgs = c("ggplot2","scales","caret","lubridate","reshape2","dplyr","leaflet","sqldf","doParallel","cowplot","htmlwidgets","IRdisplay","corrplot","ModelMetrics")

install.packages("ggplot2",dependencies=T)
install.packages("scales",dependencies=T)
install.packages("caret",dependencies=T)
install.packages("lubridate",dependencies=T)
install.packages("reshape2",dependencies=T)
install.packages("dplyr",dependencies=T)
install.packages("leaflet",dependencies=T)
install.packages("sqldf",dependencies=T)
install.packages("ggplot2",dependencies=T)
install.packages("doParallel",dependencies=T)
install.packages("htmlwidgets",dependencies=T)
install.packages("IRdisplay",dependencies=T)
install.packages("corrplot",dependencies=T)
install.packages("ModelMetrics",dependencies=T)
install.packages("magrittr",dependencies=T)
install.packages("pacman")
remotes::install_github("cran/dplyr")
pacman::p_load("ggplot2","scales","caret","lubridate","reshape2","dplyr","leaflet","sqldf","doParallel","cowplot","htmlwidgets","IRdisplay","corrplot","ModelMetrics")